### ISSUE TITLE
Meaning of 'energy_grad'

### ISSUE THREAD

**Issue by Nokimann** [learningmatter-mit/NeuralForceField#15]
I'm reading your tutorials. Thank you for the tutorials.

Is 'energy_grad' the same as the 'force' data?

The 'force' data seems to be a 3-dimensional vector.
Does the 'energy_grad' have the same dimension and meaning of property for molecules?

Can I ask further about the tutorials?

**Comment by simonaxelrod** [comment]
Same as the forces, but with a negative sign

**Comment by Nokimann** [comment]
Thank you!

**Comment by Nokimann** [comment]
The force might be calculated minus the energy derivative with the trained model function.

Is it better to use the derivative instead of direct training of forces as target values?

**Comment by Nokimann** [comment]
You have guided me well enough. Thank you so much!
