### ISSUE TITLE
Missing c6ab.npy

### ISSUE THREAD

**Issue by sli259** [learningmatter-mit/NeuralForceField#16]
I am trying to run the tutorial but keep getting this error:

```
from nff.train import Trainer, get_trainer, get_model, load_model, loss, hooks, metrics, evaluate

FileNotFoundError: [Errno 2] No such file or directory: '~/miniconda3/envs/nff/lib/python3.8/site-packages/nff/utils/table_data/c6ab.npy'

```
Can you let me know how to fix this?

**Comment by simonaxelrod** [comment]
Hey @sli259 - can you try cloning the repo and putting it in your Python path, instead of pip installing it? That should fix the issue (I still haven't figured out how to make this work with pip)

**Comment by gridley** [comment]
I have a fix for this that I'm going to make a PR for now!

**Comment by simonaxelrod** [comment]
Thank you! I struggled with it for a while and couldn't figure out how to fix it
