### ISSUE TITLE
Please add a license

### ISSUE THREAD

**Issue by mattwelborn** [learningmatter-mit/NeuralForceField#2]
Thank you for publishing this code! Based on other repositories in your group, it seems this repository is meant to be open-source. However, it is not open-source until a license is added. Please add a(n open-source) license if you do intend for this code to be open-source.

https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository#choosing-the-right-license

**Comment by mattwelborn** [comment]
(Without a license, it's a legal grey area as to whether I am permitted to run this code.)

**Comment by rgbombarelli** [comment]
You got us! We were trying to entrap you \s

We’ll fix ASAP xD

**Comment by simonaxelrod** [comment]
Hi @mattwelborn - the license is now posted [here](https://github.com/learningmatter-mit/NeuralForceField/blob/master/LICENSE)

**Comment by mattwelborn** [comment]
Thanks!
