### ISSUE TITLE
Potential error in SMILES string for tutorial training data

### ISSUE THREAD

**Issue by rsokl** [learningmatter-mit/NeuralForceField#3]
Hello! While working through your tutorial (which is great!) I noted that the SMILES string for the dataset located at `NeuralForceField/tutorials/data/dataset.pth.tar` is COC, which is

![image](https://user-images.githubusercontent.com/29104956/140828653-64e29413-01bb-46d2-ab42-292848665c2d.png)

however, when I plot a datum for myself:

![image](https://user-images.githubusercontent.com/29104956/140828761-f0cd7a00-cb63-4f9f-8032-66cd9155549f.png)

or consult the first step of the MD sim from part 3:

![image](https://user-images.githubusercontent.com/29104956/140828798-1f9f777f-a79d-478b-bdb2-98e3510f3dd6.png)

it looks like this is actually ethanol and that the SMILES string ought to be OCC.

Does this seem right to you, or am I missing something?

**Comment by simonaxelrod** [comment]
@rsokl You're definitely right! I've made the change [here](https://github.com/learningmatter-mit/NeuralForceField/commit/99a797eeeaea16b4fcb94e32e783450f1316ee00)
