### ISSUE TITLE
'elec_config.json' file is not installed correctly

### ISSUE THREAD

**Issue by Nanco-L** [learningmatter-mit/NeuralForceField#4]
Hello, I try to use `NeuralForceField` code for using PAINN model.
After download zip file, I install `nff` with `python setup.py install` command.
And I test `09_painn.ipynb` file in tutorial.
But I got the error
```
No such file or directory: '/home/sr6/kyuhyun9.lee/env_ML/lib/python3.6/site-packages/nff-1.0.0-py3.6.egg/nff/utils/elec_config.json'
```
The error is fixed simply by copying `elec_config.json` file into the installed directory.
I think the problem can easily solved by changing setup.py.

**Comment by simonaxelrod** [comment]
Hey @Nanco-L, [this commit](https://github.com/learningmatter-mit/NeuralForceField/commit/82f5c873285669849b56c659d790c478e06806c9) should fix the problem. Let me know if it works for you

**Comment by Nanco-L** [comment]
Thank you for response, @simonaxelrod. Because I already install `nff` and fix the problem with my own way, I can't test the difference of new commit (sorry I'm lazy..). But, I think new commit can solve my problem.

**Comment by simonaxelrod** [comment]
Sounds good, I'll close this
