### ISSUE TITLE
GraphAttention.message only uses ij contributions -- never ji -- to form message

### ISSUE THREAD

**Issue by rsokl** [learningmatter-mit/NeuralForceField#6]
`a_ji` is not incorporated into the actual message that gets returned by `GraphAttention.message`:

https://github.com/learningmatter-mit/NeuralForceField/blob/f06f1a1aae2bb95a92cdf7657863e5f6a21bd983/nff/nn/modules/schnet.py#L293-L305

**Comment by simonaxelrod** [comment]
Good find! [This commit](https://github.com/learningmatter-mit/NeuralForceField/commit/18408c6a62ba1dd72a6a8e63c857e08f00b91c0a) fixes it. The graph attention code was written a while back and I don't think we've used it any of our models. So I would be extra careful with it, and also with anything that isn't referenced in a tutorial (and hence thoroughly tested)

**Comment by rsokl** [comment]
Thanks for the tip 😃  ! I just came across it by chance as I was going through some of the source code -- my IDE highlighted the unused variable. I'm not using that particular code.

**Comment by simonaxelrod** [comment]
Awesome, thanks for letting us know! Gotta love those IDEs
