### ISSUE TITLE
Dimenet tutorials cannot run

### ISSUE THREAD

**Issue by GUYYYUG** [learningmatter-mit/NeuralForceField#9]
Hi,
I really appreciate what you did in the tutorials ,but I still met a problem when I try to train a dimenet network.
First , I make the dataset according to '/NeuralForceField/tutorials/data/create_dataset_from_file.ipynb' step by step,everything goes well.
Then I try to replace ' /NeuralForceField/tutorials/data/dataset.pth.tar' with my dataset in 06_dimenet.ipynb, however,it dosn't work.
the error is:
```
_---> 44     index = index.view(index_size).expand_as(src)
     47 # Generate output tensor if not given.
     48 if out is None:
RuntimeError: shape '[46080]' is invalid for input of size 360
```
Even I try not to replace the dataset, just run 06_dimenet.ipynb without any change,this error still occurs.I'm very confused with this error ,hope to get  your reply.

thanks!

**Comment by simonaxelrod** [comment]
Hey @GUYYYUG - glad you're enjoying it! Let me take a look at this, and I'll get back to you soon.

**Comment by LingsparkQ** [comment]
Hi, I met the same problem as GUYYYUG mentioned above. I am wondering how to tackle it as well. Thanks!

**Comment by simonaxelrod** [comment]
Hi everyone - [this commit](https://github.com/learningmatter-mit/NeuralForceField/commit/d81762d204e96b40bdac66fa9eca9ec400820a5f) should fix the issue. Does the tutorial run now?

**Comment by LingsparkQ** [comment]
@simonaxelrod Hi, Thank you very much. It seems that this notebook works now. @GUYYYUG Thanks for your raising the issue as well. Feel free to contact me supposing you would like anyone to talk about GNN for molecular problems. BTW, I am now a toddler in this field from China.

**Comment by simonaxelrod** [comment]
Great, glad it works now! I'm going to close the issue but feel free to respond again if there are any other problems.

**Comment by GUYYYUG** [comment]
Thanks very much for your latest commit!!  @simonaxelrod 
I am recently doing an internship about  molecular,however, I know little about this area. I am a junior undergraduate student at THU.glad to talk with you! @LingsparkQ
